// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_fir,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=267,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4418,HLS_SYN_LUT=14180,HLS_VERSION=2022_1}" *)

module fir (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y,
        y_ap_vld,
        x
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] y;
output   y_ap_vld;
input  [31:0] x;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_ap_vld;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [1023:0] fir_int_int_shift_reg;
wire   [1023:0] tmp_s_fu_81_p5;
reg   [1023:0] tmp_s_reg_119;
wire    ap_CS_fsm_state3;
wire    grp_fir_Pipeline_Time_delay_loop_fu_57_ap_start;
wire    grp_fir_Pipeline_Time_delay_loop_fu_57_ap_done;
wire    grp_fir_Pipeline_Time_delay_loop_fu_57_ap_idle;
wire    grp_fir_Pipeline_Time_delay_loop_fu_57_ap_ready;
wire   [1023:0] grp_fir_Pipeline_Time_delay_loop_fu_57_p_out;
wire    grp_fir_Pipeline_Time_delay_loop_fu_57_p_out_ap_vld;
wire    grp_fir_Pipeline_MAC_fu_63_ap_start;
wire    grp_fir_Pipeline_MAC_fu_63_ap_done;
wire    grp_fir_Pipeline_MAC_fu_63_ap_idle;
wire    grp_fir_Pipeline_MAC_fu_63_ap_ready;
wire   [31:0] grp_fir_Pipeline_MAC_fu_63_acc_out;
wire    grp_fir_Pipeline_MAC_fu_63_acc_out_ap_vld;
reg    grp_fir_Pipeline_Time_delay_loop_fu_57_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_fir_Pipeline_MAC_fu_63_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [7:0] trunc_ln260_fu_77_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 fir_int_int_shift_reg = 1024'd0;
#0 grp_fir_Pipeline_Time_delay_loop_fu_57_ap_start_reg = 1'b0;
#0 grp_fir_Pipeline_MAC_fu_63_ap_start_reg = 1'b0;
end

fir_fir_Pipeline_Time_delay_loop grp_fir_Pipeline_Time_delay_loop_fu_57(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fir_Pipeline_Time_delay_loop_fu_57_ap_start),
    .ap_done(grp_fir_Pipeline_Time_delay_loop_fu_57_ap_done),
    .ap_idle(grp_fir_Pipeline_Time_delay_loop_fu_57_ap_idle),
    .ap_ready(grp_fir_Pipeline_Time_delay_loop_fu_57_ap_ready),
    .fir_int_int_shift_reg_load(fir_int_int_shift_reg),
    .p_out(grp_fir_Pipeline_Time_delay_loop_fu_57_p_out),
    .p_out_ap_vld(grp_fir_Pipeline_Time_delay_loop_fu_57_p_out_ap_vld)
);

fir_fir_Pipeline_MAC grp_fir_Pipeline_MAC_fu_63(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fir_Pipeline_MAC_fu_63_ap_start),
    .ap_done(grp_fir_Pipeline_MAC_fu_63_ap_done),
    .ap_idle(grp_fir_Pipeline_MAC_fu_63_ap_idle),
    .ap_ready(grp_fir_Pipeline_MAC_fu_63_ap_ready),
    .tmp_2(tmp_s_reg_119),
    .acc_out(grp_fir_Pipeline_MAC_fu_63_acc_out),
    .acc_out_ap_vld(grp_fir_Pipeline_MAC_fu_63_acc_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fir_Pipeline_MAC_fu_63_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_fir_Pipeline_MAC_fu_63_ap_start_reg <= 1'b1;
        end else if ((grp_fir_Pipeline_MAC_fu_63_ap_ready == 1'b1)) begin
            grp_fir_Pipeline_MAC_fu_63_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fir_Pipeline_Time_delay_loop_fu_57_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_fir_Pipeline_Time_delay_loop_fu_57_ap_start_reg <= 1'b1;
        end else if ((grp_fir_Pipeline_Time_delay_loop_fu_57_ap_ready == 1'b1)) begin
            grp_fir_Pipeline_Time_delay_loop_fu_57_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fir_int_int_shift_reg <= tmp_s_fu_81_p5;
        tmp_s_reg_119 <= tmp_s_fu_81_p5;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_fir_Pipeline_Time_delay_loop_fu_57_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_fir_Pipeline_MAC_fu_63_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y_ap_vld = 1'b1;
    end else begin
        y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_fir_Pipeline_Time_delay_loop_fu_57_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_fir_Pipeline_MAC_fu_63_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_fir_Pipeline_MAC_fu_63_ap_start = grp_fir_Pipeline_MAC_fu_63_ap_start_reg;

assign grp_fir_Pipeline_Time_delay_loop_fu_57_ap_start = grp_fir_Pipeline_Time_delay_loop_fu_57_ap_start_reg;

assign tmp_s_fu_81_p5 = {{grp_fir_Pipeline_Time_delay_loop_fu_57_p_out[1023:8]}, {trunc_ln260_fu_77_p1}};

assign trunc_ln260_fu_77_p1 = x[7:0];

assign y = grp_fir_Pipeline_MAC_fu_63_acc_out;

endmodule //fir
